# Generated by Django 6.0.4 on 2026-04-23 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_category', models.CharField(choices=[('rodent', 'Rodent'), ('flying_insect', 'Flying Insect'), ('cockroach', 'Cockroach'), ('mosquito', 'Mosquito'), ('termite', 'Termite'), ('general', 'General')], help_text='Determines which child table holds detailed data.', max_length=20)),
                ('observation_time', models.DateTimeField(auto_now_add=True, help_text='Auto-set to exact timestamp of observation entry.')),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='jobs.servicejob')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_observation',
            },
        ),
        migrations.CreateModel(
            name='RodentObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodent_box_id', models.CharField(help_text='e.g. Box-A1', max_length=20)),
                ('location_in_premises', models.CharField(help_text='e.g. Kitchen corner, Near drain', max_length=200)),
                ('rats_found_count', models.PositiveIntegerField(default=0)),
                ('bait_consumed', models.BooleanField(default=False)),
                ('bait_replaced', models.BooleanField(default=False)),
                ('droppings_observed', models.BooleanField(default=False)),
                ('gnaw_marks', models.BooleanField(default=False)),
                ('activity_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('photo_evidence', models.ImageField(blank=True, help_text='S3 key (production) or media/observations/ path (development).', null=True, upload_to='observations/')),
                ('technician_remarks', models.TextField(blank=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rodent_detail', to='observations.serviceobservation')),
            ],
            options={
                'db_table': 'rodent_observation',
            },
        ),
        migrations.CreateModel(
            name='MosquitoObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_area', models.CharField(help_text='e.g. Garden, drainage, stairwell', max_length=200)),
                ('fogging_done', models.BooleanField(default=False)),
                ('chemical_used', models.CharField(blank=True, max_length=100)),
                ('breeding_sites_found', models.PositiveIntegerField(default=0)),
                ('breeding_sites_eliminated', models.PositiveIntegerField(default=0)),
                ('larval_activity', models.BooleanField(default=False)),
                ('adult_mosquito_density', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='observations/')),
                ('technician_remarks', models.TextField(blank=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mosquito_detail', to='observations.serviceobservation')),
            ],
            options={
                'db_table': 'mosquito_observation',
            },
        ),
        migrations.CreateModel(
            name='GeneralObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_type_observed', models.CharField(help_text='e.g. Bed Bug, Ant, Bird, Silverfish, Lizard, Other', max_length=100)),
                ('location_in_premises', models.CharField(help_text='e.g. Master bedroom, Ceiling gap', max_length=200)),
                ('pest_count', models.PositiveIntegerField(default=0, help_text='Use 0 if uncountable.')),
                ('treatment_applied', models.BooleanField(default=False)),
                ('treatment_description', models.CharField(blank=True, help_text='e.g. Spray, Trap placed, Gel applied', max_length=300)),
                ('activity_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('recommended_action', models.TextField(blank=True, help_text='Technician recommendation for follow-up.')),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='observations/')),
                ('technician_remarks', models.TextField(blank=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_detail', to='observations.serviceobservation')),
            ],
            options={
                'db_table': 'general_observation',
            },
        ),
        migrations.CreateModel(
            name='FlyingInsectObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flycatcher_machine_id', models.CharField(help_text='e.g. FC-01', max_length=20)),
                ('machine_location', models.CharField(help_text='e.g. Near entrance, Reception', max_length=200)),
                ('insects_trapped_count', models.PositiveIntegerField(default=0)),
                ('insect_types_trapped', models.JSONField(default=list, help_text="Array of insect types observed e.g. ['Flies', 'Moths']")),
                ('glue_board_changed', models.BooleanField(default=False)),
                ('glue_board_condition', models.CharField(blank=True, choices=[('good', 'Good'), ('dirty', 'Dirty'), ('replaced', 'Replaced')], max_length=10)),
                ('machine_functional', models.BooleanField(default=True, help_text='R-06: If FALSE, triggers immediate Critical alert.')),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='observations/')),
                ('technician_remarks', models.TextField(blank=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flying_insect_detail', to='observations.serviceobservation')),
            ],
            options={
                'db_table': 'flying_insect_observation',
            },
        ),
        migrations.CreateModel(
            name='CockroachObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='e.g. CG-01', max_length=20)),
                ('location_in_premises', models.CharField(help_text='e.g. Under kitchen sink', max_length=200)),
                ('cockroaches_found', models.PositiveIntegerField(default=0)),
                ('gel_applied', models.BooleanField(default=False)),
                ('gel_consumed', models.BooleanField(default=False)),
                ('activity_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('infestation_area', models.CharField(blank=True, max_length=100)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='observations/')),
                ('technician_remarks', models.TextField(blank=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cockroach_detail', to='observations.serviceobservation')),
            ],
            options={
                'db_table': 'cockroach_observation',
            },
        ),
        migrations.CreateModel(
            name='TermiteObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(help_text='e.g. TB-01', max_length=20)),
                ('station_location', models.CharField(max_length=200)),
                ('termites_found', models.BooleanField(default=False)),
                ('bait_consumed', models.BooleanField(default=False)),
                ('bait_replaced', models.BooleanField(default=False)),
                ('mud_tubes_found', models.BooleanField(default=False, help_text='Subterranean termite evidence.')),
                ('wood_damage_observed', models.BooleanField(default=False)),
                ('damage_severity', models.CharField(choices=[('none', 'None'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=10)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='observations/')),
                ('technician_remarks', models.TextField(blank=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termite_detail', to='observations.serviceobservation')),
            ],
            options={
                'db_table': 'termite_observation',
            },
        ),
    ]
