# Generated by Django 6.0.4 on 2026-04-23 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public-facing unique job identifier. Auto-generated.', unique=True)),
                ('created_by_role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor')], help_text='Role of the user who created this job. Stored for audit.', max_length=20)),
                ('site_address', models.TextField()),
                ('service_type', models.CharField(choices=[('rodent_control', 'Rodent Control'), ('flying_insect', 'Flying Insect'), ('cockroach', 'Cockroach'), ('termite', 'Termite'), ('mosquito', 'Mosquito'), ('general', 'General'), ('bed_bug', 'Bed Bug')], max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('observations_recorded', 'Observations Recorded'), ('completed', 'Completed'), ('report_sent', 'Report Sent')], default='scheduled', max_length=30)),
                ('scheduled_datetime', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.TextField(blank=True)),
                ('customer_sign_required', models.BooleanField(default=False)),
                ('customer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('is_report_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='accounts.customer')),
            ],
            options={
                'db_table': 'service_job',
                'ordering': ['-scheduled_datetime'],
            },
        ),
    ]
