# Generated by Django 6.0.4 on 2026-05-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
