# Generated by Django 6.0.4 on 2026-04-23 06:44

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('email_type', models.CharField(choices=[('otp_login', 'OTP Login'), ('job_started', 'Job Started'), ('observation_update', 'Observation Update'), ('completion_report', 'Completion Report'), ('high_activity_alert', 'High Activity Alert'), ('maintenance_alert', 'Maintenance Alert')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp email was dispatched via Celery.')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery async task UUID for tracking.', max_length=36)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if delivery failed.')),
                ('pdf_attached', models.BooleanField(default=False, help_text='Whether a PDF was attached to this email.')),
                ('job', models.ForeignKey(blank=True, help_text='Nullable for non-job emails (e.g. OTP login emails).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='jobs.servicejob')),
            ],
            options={
                'db_table': 'email_log',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(help_text='S3 key (production) or media/reports/ path (development).', upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_size_kb', models.PositiveIntegerField(default=0)),
                ('includes_signature', models.BooleanField(default=False)),
                ('download_token', models.UUIDField(default=uuid.uuid4, help_text='Secure UUID token for customer download link.', unique=True)),
                ('token_expires_at', models.DateTimeField(default=reports.models.default_token_expiry, help_text='Default: 7 days after generation.')),
                ('generated_by', models.ForeignKey(blank=True, help_text='Nullable for auto-generation on job completion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_report', to='jobs.servicejob')),
            ],
            options={
                'db_table': 'pdf_report',
            },
        ),
    ]
