# Generated by Django 6.0.4 on 2026-04-23 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('recommendation', 'Recommendation'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('maintenance', 'Maintenance'), ('info', 'Info')], max_length=20)),
                ('pest_category', models.CharField(choices=[('rodent', 'Rodent'), ('flying_insect', 'Flying Insect'), ('cockroach', 'Cockroach'), ('termite', 'Termite'), ('mosquito', 'Mosquito'), ('general', 'General')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(help_text='Full alert message with specific recommendations.')),
                ('rule_triggered', models.CharField(help_text='Which SmartAlertEngine rule fired e.g. R-01, R-03, R-06', max_length=100)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes entered by supervisor/admin when resolving. [NEW v2]')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Was this alert also emailed to admin/supervisor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_alerts', to='jobs.servicejob')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_alerts', to='observations.serviceobservation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'smart_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
